// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkH5He6gdql-Sjem4Yfi9aReW_LQTQD0E',
    appId: '1:673872379502:web:4af2b5e6fb4f66dd16707f',
    messagingSenderId: '673872379502',
    projectId: 'flutter-formation-c0c0c',
    authDomain: 'flutter-formation-c0c0c.firebaseapp.com',
    storageBucket: 'flutter-formation-c0c0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUyYfwhhiNi9xHJtucvpAdkxl9pWkqxg',
    appId: '1:673872379502:android:b7200d180e42ea0416707f',
    messagingSenderId: '673872379502',
    projectId: 'flutter-formation-c0c0c',
    storageBucket: 'flutter-formation-c0c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOJ8pkGl0V5qCe_581H9whtmOvb62gzms',
    appId: '1:673872379502:ios:9d44fb8025e26dac16707f',
    messagingSenderId: '673872379502',
    projectId: 'flutter-formation-c0c0c',
    storageBucket: 'flutter-formation-c0c0c.appspot.com',
    iosBundleId: 'com.example.hellowWord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOJ8pkGl0V5qCe_581H9whtmOvb62gzms',
    appId: '1:673872379502:ios:8b8788d3b32236f516707f',
    messagingSenderId: '673872379502',
    projectId: 'flutter-formation-c0c0c',
    storageBucket: 'flutter-formation-c0c0c.appspot.com',
    iosBundleId: 'com.example.hellowWord.RunnerTests',
  );
}
